live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.7

[window.padding]
x = 3
y = 0

[font]
size = 8.0

[font.bold]
family = "ComicShannsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "ComicShannsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "ComicShannsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Medium"

[colors.normal]
black = "#000000"
red = "#c01020"
green = "#98c66c"
yellow = "#dfd750"
blue = "#00afbf"
magenta = "#af5fd7"
cyan = "#00afbf"
white = "#e4e4e4"

[colors.primary]
foreground = "#e4e4e4"
background = "#000000"

[colors]
cursor = { text = "#000000", cursor = "#af5fd7" }

[bell]
duration = 0

[cursor]
style = { shape = "block", blinking = "Off" }

[mouse]
hide_when_typing = true
